apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-agent-target-access
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "target-apps.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.agentServiceAccount }}
    namespace: {{ .Values.agentNamespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-target-reader
  apiGroup: rbac.authorization.k8s.io
