apiVersion: v1
kind: ConfigMap
metadata:
  name: poisoned-logs
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "target-apps.labels" . | nindent 4 }}
data:
  log-output.txt: |
{{ .Files.Get "files/payload.txt" | indent 4 }}
