apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
  namespace: {{ .Values.targetNamespace }}
  labels:
    app: inventory-app
    {{- include "target-apps.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
        - name: app
          image: {{ .Values.targetImage }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                cat /config/log-output.txt
                sleep 30
              done
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
      volumes:
        - name: config
          configMap:
            name: poisoned-logs
