apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.image.attacker.name }}
  namespace: {{ .Values.attackerNamespace }}
  labels:
    {{- include "attack.labels" . | nindent 4 }}
    app.kubernetes.io/component: attacker
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.image.attacker.name }}:{{ .Values.image.attacker.tag }}
  source:
    type: Git
    git:
      uri: {{ .Values.build.attacker.git.uri }}
      ref: {{ .Values.build.attacker.git.ref }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: build/Dockerfile
  triggers:
    - type: ConfigChange
  resources:
    {{- toYaml .Values.build.attacker.resources | nindent 4 }}
