apiVersion: v1
kind: Service
metadata:
  name: neo-attacker
  namespace: {{ .Values.attackerNamespace }}
  labels:
    app: attacker
    {{- include "attack.labels" . | nindent 4 }}
spec:
  selector:
    app: attacker
  ports:
    - name: ttyd
      port: 7681
      targetPort: ttyd
      protocol: TCP
